name: Terraform AWS Infrastructure CI/CD

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  ##### INIT & VALIDATE
  init-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials for Init/Validate Role (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::100403449592:role/TerraformPlanRole
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.x

      - name: Terraform Init
        run: terraform init
        env:
          AWS_EC2_METADATA_DISABLED: true
        working-directory: ./ 


      - name: Terraform Fmt Check
        run: terraform fmt -check
        working-directory: ./

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
        working-directory: ./

      - name: Run TFLint
        run: tflint --init && tflint
        working-directory: ./

  ##### PLAN
  plan:
    runs-on: ubuntu-latest
    needs: init-validate 

    permissions:
      id-token: write 
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials for Plan Role (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::100403449592:role/TerraformPlanRole 
          aws-region: eu-central-1 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./

      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ./tfplan
          retention-days: 1

  ##### APPLY 
  apply:
    # if : github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: plan
    environment:
      name: production # Możesz użyć 'staging' lub 'production'

    permissions:
      id-token: write 
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials for Apply Role (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::100403449592:role/TerraformApplyRole 
          aws-region: eu-central-1 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: ./
      
      - name: Terraform Init (Download Providers)
        run: terraform init
        working-directory: ./

      - name: Terraform Apply
        run: terraform apply tfplan
        working-directory: ./
